### ISSUE TITLE
 Handle Chargebee unexpected error

### ISSUE THREAD

**Issue by ghost** [globalis-ms/chargebee-php-sdk#1]
If there is an unexpected error (for example: Chargebee DNS problem, error 500 without body), The error handler is not working:

![image](https://user-images.githubusercontent.com/33837038/154475965-57b62763-a165-4f27-a956-e2f1205c2935.png)

To fix that, can you apply this?

File : nathandunn/chargebee-php-sdk/src/HttpClient/Exception/ApiExceptionHandler.php
![image](https://user-images.githubusercontent.com/33837038/154476005-526dc9e2-a309-41de-81e6-95e8a31228b7.png)

**Comment by pierre-dargham** [comment]
Thanks @JAmathieu  :+1:
Fixed in https://github.com/globalis-ms/chargebee-php-sdk/commit/74a98600cf7d7390fe2a56bf833dfbac4bbde3d4
